# Generated by Django 5.1.4 on 2024-12-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='song',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
