# Generated by Django 5.1.4 on 2024-12-30 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='playlist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
