# Generated by Django 5.1.4 on 2024-12-30 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_average_rating_song_rating_count'),
        ('reviews', '0002_rename_song_review_music_remove_review_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('music', 'reviewer')},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
    ]
